version: '3'

services:
  mailfort:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8350:8080"
      - "44350:44044"
    env_file:
      - .env
    environment:
      - CONFIG_PATH=./config/prod.yaml
