env: "local" # local, dev, prod

app:
  name: "mailfort"
  version: "1.0.0"

http:
  host: "0.0.0.0"
  port: 8080
  allow_origins: "*" # Example: 127.0.0.1, example.com

grpc:
  port: 44044
  timeout: 10h

log:
  slog:
    add_source: true
    level: "debug"
    format: "pretty"
    pretty:
      fields_format: "json"
      emoji: true
      # time_layout: "15:04:05.000000"

mail:
  host: smtp.mail.ru
  port: 587
  username: user@mail.ru
  password: pass
