env: "prod" # local, dev, prod

app:
  name: "mailfort"
  version: "1.0.0"

http:
  host: "0.0.0.0"
  port: 8080
  allow_origins: "*" # Example: 127.0.0.1, example.com

grpc:
  port: 44044
  timeout: 10h

log:
  slog:
    add_source: true
    level: "info"
    format: "json"
